config/routes.rb
Rails.application.routes.draw do
  root 'users#index'
  resources :users

end

app/models/user.rb
class User < ActiveRecord::Base
  has_one_attache :avatar
  has_many_attaches :photos
  validates_presence_of :name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include ActiveParams
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    User.where("created_at < ?", ENV.fetch("EXPIRE_SECONDS") { 30.minutes }.to_i.seconds.ago).each(&:destroy)
    @users = User.all.page(params[:page])
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def icon(name, text)
    content_tag(:span, nil, class: "fa fa-#{name}") +
    "\n" + h(text)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.slim
doctype 5
html(lang='en')
  head
    title Attache demo
    meta(charset='utf-8')
    meta(http-equiv='X-UA-Compatible' content='IE=Edge,chrome=1')
    meta(name='description' content='')
    meta(name='viewport' content='width=device-width, initial-scale=1.0')

    /![if lt IE 9]
      = javascript_include_tag '//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js'
    = javascript_include_tag  'application', 'data-turbolinks-track' => true
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = csrf_meta_tags

  body class=page_class
    nav.navbar.navbar-default.navbar-static-top
      .container
        .navbar-header
          button.navbar-toggle(type='button' data-toggle='collapse' data-target='.navbar-responsive-collapse')
            span.icon-bar
            span.icon-bar
            span.icon-bar
          a.navbar-brand(href=root_path)
            ' Demo
        #navbar.navbar-collapse.collapse.nav-app-collapse.navbar-responsive-collapse.topnav
          ul.nav.navbar-nav
            li= link_to "attache server", "https://github.com/choonkeat/attache#readme", target: "_blank"
            li= link_to "attache-rails gem", "https://github.com/choonkeat/attache-rails#readme", target: "_blank"

    .container
      .content
        .row
          .col-sm-12
            = yield

    footer
      .container
        .row
          .col-sm-12

app/views/users/_form.html.slim
.row
  .col-sm-6
    .panel.panel-default
      .panel-heading
        h4 Schema
      .panel-body
        pre
          code
            ' create_table "users" do |t|
                t.string "name"
                t.json   "avatar"
                t.json   "photos"
              end

  .col-sm-6
    .panel.panel-default
      .panel-heading
        h4 Model
      .panel-body
        pre
          code
            ' class User &lt; ActiveRecord::Base
                has_one_attache   :avatar
                has_many_attaches :photos
                validates_presence_of :name
              end

.panel.panel-default
  .panel-heading
    h4 Form
  .panel-body
    = simple_form_for @user, html: { class: 'form-horizontal col-sm-12' } do |f|
      = f.input :name

      = f.input :avatar do
        pre
          code= f.object.avatar.to_json
        pre
          code
            ' = f.file_field :avatar, f.object.avatar_options('190x190#', placeholder: image_path('placeholder.png'))

        = f.file_field :avatar, f.object.avatar_options('190x190#', placeholder: image_path('placeholder.png'))

      = f.input :photos do
        pre
          code= f.object.photos.to_json
        pre
          code
            ' = f.file_field :photos, f.object.photos_options('190x75#', placeholder: image_path('placeholder.png'))
        = f.file_field :photos, f.object.photos_options('190x75#', placeholder: image_path('placeholder.png'))

      .form-action.form-group
        .form-left-offset.form-right
          - if f.object.new_record?
            => f.button :button, class: 'btn btn-primary', data: { disable_with: t('helpers.disable_with') } do
              = icon 'check-square-o', t('helpers.submit.create', model: f.object.class.model_name.human.titleize)
            = ' or '
            = link_to t('.cancel', default: t('helpers.links.cancel')), users_path
          - else
            => f.button :button, class: 'btn btn-primary', data: { disable_with: t('helpers.disable_with') } do
              = icon 'check-square-o', t('helpers.submit.update', model: f.object.class.model_name.human.titleize)
            = ' or '
            = link_to t('.cancel', default: t('helpers.links.cancel')), user_path(@user)
            .pull-right
              = link_to user_path(@user), class: 'btn btn-danger', method: :delete, data: { confirm: t('helpers.confirm'), disable_with: t('helpers.disable_with') } do
                = icon 'trash', t('.destroy', default: t('helpers.links.destroy'))

app/views/users/edit.html.slim
.page-header
  h1 Edit User

= render 'form'

app/views/users/index.html.slim
.jumbotron
  h1
    => link_to "Attache server", "https://github.com/choonkeat/attache#readme", target: "_blank"
    ' demo
  p
    => link_to "This demo app", "https://github.com/choonkeat/attache-railsapp", target: "_blank"
    ' uses the
    => link_to "attache-rails gem", "https://github.com/choonkeat/attache-rails#readme", target: "_blank"
    ' to integrate with a free &amp; open source
    = link_to "attache file server", "https://github.com/choonkeat/attache#readme", target: "_blank"
  p
    ' On this demo server, files are not backed up to any cloud storage and records are purged periodically.
  p
    = link_to "» Read more about attache", "https://github.com/choonkeat/attache#readme", target: "_blank", class: "btn btn-lg btn-primary"

.pull-right
  = link_to icon('plus', t('helpers.links.new', model: User.model_name.human)), new_user_path, class: 'btn btn-primary'

table.table.table-hover
  thead
    tr
      th User name
      th
  tbody
    - @users.each do |user|
      tr
        td= link_to user.name, user
        td.text-right
          .btn-group
            = link_to user_path(user), class: 'btn btn-success btn-sm' do
              = icon 'eye'  , t('helpers.links.show', model: User.model_name.human)
            = link_to edit_user_path(user), class: 'btn btn-warning btn-sm' do
              = icon 'edit' , t('helpers.links.edit', model: User.model_name.human)
          =< link_to user_path(user), class: 'btn btn-danger btn-sm', method: :delete, data: { confirm: 'Are you sure?' } do
            = icon 'trash', t('helpers.links.destroy', model: User.model_name.human)

hr

.row
  .col-sm-6
    = page_entries_info @users, entry_name: User.model_name.human
  .col-sm-6
    = paginate(@users)

app/views/users/new.html.slim
.page-header
  h1 New User

= render 'form'

app/views/users/show.html.slim
.page-header
  h1 User

.panel.panel-default
  .panel-heading
    h4 Name
  .panel-body
    pre.pre-x-scrollable
      code= @user.name.to_json
  .panel-heading
    h4 Avatar
  .panel-body
    pre.pre-x-scrollable
      code= JSON.pretty_generate @user.avatar if @user.avatar.present?

    pre.pre-x-scrollable
      code
        ' = image_tag @user.avatar_url(fit: 'crop', w: 100, h: 100)

    = image_tag @user.avatar_url(fit: 'crop', w: 100, h: 100) if @user.avatar.present?
  .panel-heading
    h4 Photos
  .panel-body
    pre.pre-x-scrollable
      code= JSON.pretty_generate @user.photos if @user.photos.present?
    pre.pre-x-scrollable
      code
        ' - @user.photos_urls(fit: 'crop', w: 200, h: 200).each do |url|
            => image_tag url

    - @user.photos_urls(fit: 'crop', w: 200, h: 200).each do |url|
      => image_tag url

.btn-group
  = link_to edit_user_path(@user), class: 'btn btn-warning' do
    = icon 'edit' , t('helpers.links.edit', model: User.model_name.human)
= ' or '
= link_to t('.cancel', default: t('helpers.links.cancel')), users_path
.pull-right
  = link_to user_path(@user), class: 'btn btn-danger', method: :delete, data: { confirm: 'Are you sure?' } do
    = icon 'trash', t('helpers.links.destroy', model: User.model_name.human)